### ISSUE TITLE
PHP 8 / Deprecated: Optional parameter

### ISSUE THREAD

**Issue by hroma** [steampixel/simplePHPPortals#1]
Hi, 
Deprecated: Optional parameter $append declared before required parameter $once is implicitly treated as a required parameter in Portal.php on line 96
The deprecation notice is triggered at the compile time, and it will be **raised even if it is not called**.

Your function has required paramaters after optional ones So the order should be:

```diff
- public static function sendBuffer($portal_name, $append = true, $once) {
+ public static function sendBuffer($portal_name, $once, $append = true) {
```
hope it helps.

**Comment by steampixel** [comment]
@hroma thanks for reporting this issue.

**Comment by steampixel** [comment]
I changed the parameters in the last version. Seems like I had left some untested code inside :-)
The parameter $append is now $prepend. And the parameter $once is now optional too like inside the static send() function.
